spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: f4kemailt3st@gmail.com
    password: owxbdgjlwnifukbv #for the password, generate it with 'password for app' of gmail settings.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
